Include Arch on channel update requests
When trying to update a nebraska channel, the server responds with a schema
missmatch error, where `arch` is missing:

```
2022/05/12 10:22:29 [WARN] error applying /src/nebraska: exit status 1

Error: Bad response: req_uri=http://nebraska:8000/api/apps/e96281a6-d1af-4bde-9a0a-97b76e56dc57/channels/f9b552a5-4a7d-4da3-980e-37cea455b1e3, response_code=400, response={"message":"request body has an error: doesn't match the schema: Error at \"/arch\": property \"arch\" is missing"}

  with nebraska_channel.pinned,
  on nebraska.tf line 41, in resource "nebraska_channel" "pinned":
  41: resource "nebraska_channel" "pinned" {
```

This adds the missing attribute to the channel update request.